services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      postgres-db:
        condition: service_healthy

networks:
  backend: {}

volumes:
  postgres_data: {}